 platform :ios, '13.0'

target 'HSWallpaperEdit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'GPUImage', '~> 0.1.7'
  pod 'JPImageresizerView', '~> 1.7.7'
  pod 'Toast-Swift', '~> 5.0.1'
end
